[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-is-website-vulnerable"
 [[plugins]]
  package = "netlify-purge-cloudflare-on-deploy"
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
	[plugins.inputs]
	baseUrl = "https://infosecdecompress.com"
	sitemapPath = "/sitemap.xml"
	providers = [
		"google",
		"bing"
	]
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "frame-ancestors 'self';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "microphone 'none'; geolocation 'none'"