name: Gatsby Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
        git-ref:
          description: Git Ref (Optional)    
          required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
